### ISSUE TITLE
Cooking oil burn time

### ISSUE THREAD

**Issue by TogyTogeh** [KaneHart/The-Next-Leap#1]
using Pam's mod cooking oil as fuel for cooking for blockheads cooker the fuel burns extremely quickly, 1 oil lasts less than 1 second requiring many stacks of oil to cook a single item

**Comment by StoneLegion** [comment]
Thank you for your bug report.

I can confirm oddly enough by default it should be 1.0 though the config generated 0.33 and none of us had changed this. I went ahead and set to 1.0 and it works a lot better. This will show up in version 1.2. If you play our server it will be fixed sooner during a nightly reboot.

Went from taking 43 oil to cook 7 times (63) foods to 14 oil to cook 7 times (63) food. That seems a better value. It's off a tiny bit so it might actually use a 15th oil for the very last 9 foods on the 7th time.

We will close this on 1.2 release. 
https://github.com/KaneHart/The-Next-Leap/commit/fb52e3b32e4a445cabbe11a29f0f924c62b20e37
