### ISSUE TITLE
1.2 - Journymap restrictions

### ISSUE THREAD

**Issue by TogyTogeh** [KaneHart/The-Next-Leap#2]
Since 1.2 release Journymap allows showing of caves and tracks mobs as default, previous restrictions to prevent this use are not longer applying

**Comment by StoneLegion** [comment]
Going to Close this. Sadly this seems to be a random bug server side of jmap. A simple reboot seems to have fixed it. We have not touched it since the launch of our server. Just randomly breaks I guess :(
