### ISSUE TITLE
Technical Lights mod with Pickaxe

### ISSUE THREAD

**Issue by TogyTogeh** [KaneHart/The-Next-Leap#4]
When breaking a technical lights mod grey lamp with a pickaxe you get a white lamp item returned.

If you use a silktouch pickaxe you can get the original grey lamp however the white lamp is not used in the creation of other colour lamps

**Comment by StoneLegion** [comment]
Fixed:
https://minecraft.curseforge.com/projects/technical-lights/files/2671026
