### ISSUE TITLE
1.5.1 - Diamond Drill (TR) recipe

### ISSUE THREAD

**Issue by TogyTogeh** [KaneHart/The-Next-Leap#6]
There are two recipes to create the Tech Reborn Diamond Drill, one with 0 energy in the unit and one with full energy in the unit, however when you go to the full energy recipe it uses a 0 energy Steel Drill from Tech reborn and the drill takes a considerable time to drain

![image](https://user-images.githubusercontent.com/46811659/52911190-7c19e380-3298-11e9-8b9b-2477095c87a7.png)

**Comment by StoneLegion** [comment]
Thanks, I should have fixed them for the next update. 
https://github.com/KaneHart/The-Next-Leap/commit/d5b956e240841c418d4b522b69c16220c1085268
